/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.3.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as agent_classic_embeddings from "../agent/classic/embeddings";
import type * as agent_classic_memory from "../agent/classic/memory";
import type * as agent_lib_actions from "../agent/lib/actions";
import type * as agent_lib_openai from "../agent/lib/openai";
import type * as agent_simple from "../agent/simple";
import type * as constants from "../constants";
import type * as crons from "../crons";
import type * as data_characters from "../data/characters";
import type * as data_map from "../data/map";
import type * as data_spritesheets_f1 from "../data/spritesheets/f1";
import type * as data_spritesheets_f2 from "../data/spritesheets/f2";
import type * as data_spritesheets_f3 from "../data/spritesheets/f3";
import type * as data_spritesheets_f4 from "../data/spritesheets/f4";
import type * as data_spritesheets_f5 from "../data/spritesheets/f5";
import type * as data_spritesheets_f6 from "../data/spritesheets/f6";
import type * as data_spritesheets_f7 from "../data/spritesheets/f7";
import type * as data_spritesheets_f8 from "../data/spritesheets/f8";
import type * as data_spritesheets_p1 from "../data/spritesheets/p1";
import type * as data_spritesheets_p2 from "../data/spritesheets/p2";
import type * as data_spritesheets_p3 from "../data/spritesheets/p3";
import type * as data_spritesheets_player from "../data/spritesheets/player";
import type * as data_spritesheets_types from "../data/spritesheets/types";
import type * as data_world from "../data/world";
import type * as debug from "../debug";
import type * as engine from "../engine";
import type * as game_input from "../game/input";
import type * as game_movement from "../game/movement";
import type * as game_state from "../game/state";
import type * as game_tick from "../game/tick";
import type * as humans from "../humans";
import type * as queryGameState from "../queryGameState";
import type * as schema_blocks from "../schema/blocks";
import type * as schema_conversations from "../schema/conversations";
import type * as schema_engine from "../schema/engine";
import type * as schema_input from "../schema/input";
import type * as schema_players from "../schema/players";
import type * as util_assertNever from "../util/assertNever";
import type * as util_geometry from "../util/geometry";
import type * as util_mappedTable from "../util/mappedTable";
import type * as util_minheap from "../util/minheap";
import type * as util_positionBuffer from "../util/positionBuffer";
import type * as util_types from "../util/types";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "agent/classic/embeddings": typeof agent_classic_embeddings;
  "agent/classic/memory": typeof agent_classic_memory;
  "agent/lib/actions": typeof agent_lib_actions;
  "agent/lib/openai": typeof agent_lib_openai;
  "agent/simple": typeof agent_simple;
  constants: typeof constants;
  crons: typeof crons;
  "data/characters": typeof data_characters;
  "data/map": typeof data_map;
  "data/spritesheets/f1": typeof data_spritesheets_f1;
  "data/spritesheets/f2": typeof data_spritesheets_f2;
  "data/spritesheets/f3": typeof data_spritesheets_f3;
  "data/spritesheets/f4": typeof data_spritesheets_f4;
  "data/spritesheets/f5": typeof data_spritesheets_f5;
  "data/spritesheets/f6": typeof data_spritesheets_f6;
  "data/spritesheets/f7": typeof data_spritesheets_f7;
  "data/spritesheets/f8": typeof data_spritesheets_f8;
  "data/spritesheets/p1": typeof data_spritesheets_p1;
  "data/spritesheets/p2": typeof data_spritesheets_p2;
  "data/spritesheets/p3": typeof data_spritesheets_p3;
  "data/spritesheets/player": typeof data_spritesheets_player;
  "data/spritesheets/types": typeof data_spritesheets_types;
  "data/world": typeof data_world;
  debug: typeof debug;
  engine: typeof engine;
  "game/input": typeof game_input;
  "game/movement": typeof game_movement;
  "game/state": typeof game_state;
  "game/tick": typeof game_tick;
  humans: typeof humans;
  queryGameState: typeof queryGameState;
  "schema/blocks": typeof schema_blocks;
  "schema/conversations": typeof schema_conversations;
  "schema/engine": typeof schema_engine;
  "schema/input": typeof schema_input;
  "schema/players": typeof schema_players;
  "util/assertNever": typeof util_assertNever;
  "util/geometry": typeof util_geometry;
  "util/mappedTable": typeof util_mappedTable;
  "util/minheap": typeof util_minheap;
  "util/positionBuffer": typeof util_positionBuffer;
  "util/types": typeof util_types;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
