/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.1.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as characterdata_data from "../characterdata/data";
import type * as characterdata_spritesheets_f1 from "../characterdata/spritesheets/f1";
import type * as characterdata_spritesheets_f2 from "../characterdata/spritesheets/f2";
import type * as characterdata_spritesheets_f3 from "../characterdata/spritesheets/f3";
import type * as characterdata_spritesheets_f4 from "../characterdata/spritesheets/f4";
import type * as characterdata_spritesheets_f5 from "../characterdata/spritesheets/f5";
import type * as characterdata_spritesheets_f6 from "../characterdata/spritesheets/f6";
import type * as characterdata_spritesheets_f7 from "../characterdata/spritesheets/f7";
import type * as characterdata_spritesheets_f8 from "../characterdata/spritesheets/f8";
import type * as characterdata_spritesheets_p1 from "../characterdata/spritesheets/p1";
import type * as characterdata_spritesheets_p2 from "../characterdata/spritesheets/p2";
import type * as characterdata_spritesheets_p3 from "../characterdata/spritesheets/p3";
import type * as characterdata_spritesheets_player from "../characterdata/spritesheets/player";
import type * as characterdata_spritesheets_types from "../characterdata/spritesheets/types";
import type * as crons from "../crons";
import type * as engine from "../engine";
import type * as gameState from "../gameState";
import type * as geometry from "../geometry";
import type * as map from "../map";
import type * as minheap from "../minheap";
import type * as players from "../players";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "characterdata/data": typeof characterdata_data;
  "characterdata/spritesheets/f1": typeof characterdata_spritesheets_f1;
  "characterdata/spritesheets/f2": typeof characterdata_spritesheets_f2;
  "characterdata/spritesheets/f3": typeof characterdata_spritesheets_f3;
  "characterdata/spritesheets/f4": typeof characterdata_spritesheets_f4;
  "characterdata/spritesheets/f5": typeof characterdata_spritesheets_f5;
  "characterdata/spritesheets/f6": typeof characterdata_spritesheets_f6;
  "characterdata/spritesheets/f7": typeof characterdata_spritesheets_f7;
  "characterdata/spritesheets/f8": typeof characterdata_spritesheets_f8;
  "characterdata/spritesheets/p1": typeof characterdata_spritesheets_p1;
  "characterdata/spritesheets/p2": typeof characterdata_spritesheets_p2;
  "characterdata/spritesheets/p3": typeof characterdata_spritesheets_p3;
  "characterdata/spritesheets/player": typeof characterdata_spritesheets_player;
  "characterdata/spritesheets/types": typeof characterdata_spritesheets_types;
  crons: typeof crons;
  engine: typeof engine;
  gameState: typeof gameState;
  geometry: typeof geometry;
  map: typeof map;
  minheap: typeof minheap;
  players: typeof players;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
